// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.2
// source: actions.proto

package actions

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ACTION int32

const (
	ACTION_NOACTION     ACTION = 0
	ACTION_LOGIN        ACTION = 1
	ACTION_LOGOUT       ACTION = 2
	ACTION_RECONNECTION ACTION = 3
	ACTION_JOINROOM     ACTION = 4
)

// Enum value maps for ACTION.
var (
	ACTION_name = map[int32]string{
		0: "NOACTION",
		1: "LOGIN",
		2: "LOGOUT",
		3: "RECONNECTION",
		4: "JOINROOM",
	}
	ACTION_value = map[string]int32{
		"NOACTION":     0,
		"LOGIN":        1,
		"LOGOUT":       2,
		"RECONNECTION": 3,
		"JOINROOM":     4,
	}
)

func (x ACTION) Enum() *ACTION {
	p := new(ACTION)
	*p = x
	return p
}

func (x ACTION) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ACTION) Descriptor() protoreflect.EnumDescriptor {
	return file_actions_proto_enumTypes[0].Descriptor()
}

func (ACTION) Type() protoreflect.EnumType {
	return &file_actions_proto_enumTypes[0]
}

func (x ACTION) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ACTION.Descriptor instead.
func (ACTION) EnumDescriptor() ([]byte, []int) {
	return file_actions_proto_rawDescGZIP(), []int{0}
}

type ACTION_ACK int32

const (
	ACTION_ACK_LOGIN_SUCCESS  ACTION_ACK = 0
	ACTION_ACK_LOGOUT_SUCCESS ACTION_ACK = 1
)

// Enum value maps for ACTION_ACK.
var (
	ACTION_ACK_name = map[int32]string{
		0: "LOGIN_SUCCESS",
		1: "LOGOUT_SUCCESS",
	}
	ACTION_ACK_value = map[string]int32{
		"LOGIN_SUCCESS":  0,
		"LOGOUT_SUCCESS": 1,
	}
)

func (x ACTION_ACK) Enum() *ACTION_ACK {
	p := new(ACTION_ACK)
	*p = x
	return p
}

func (x ACTION_ACK) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ACTION_ACK) Descriptor() protoreflect.EnumDescriptor {
	return file_actions_proto_enumTypes[1].Descriptor()
}

func (ACTION_ACK) Type() protoreflect.EnumType {
	return &file_actions_proto_enumTypes[1]
}

func (x ACTION_ACK) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ACTION_ACK.Descriptor instead.
func (ACTION_ACK) EnumDescriptor() ([]byte, []int) {
	return file_actions_proto_rawDescGZIP(), []int{1}
}

type JOINROOM_ACK int32

const (
	JOINROOM_ACK_JOINROOM_SUCCESS JOINROOM_ACK = 0
)

// Enum value maps for JOINROOM_ACK.
var (
	JOINROOM_ACK_name = map[int32]string{
		0: "JOINROOM_SUCCESS",
	}
	JOINROOM_ACK_value = map[string]int32{
		"JOINROOM_SUCCESS": 0,
	}
)

func (x JOINROOM_ACK) Enum() *JOINROOM_ACK {
	p := new(JOINROOM_ACK)
	*p = x
	return p
}

func (x JOINROOM_ACK) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JOINROOM_ACK) Descriptor() protoreflect.EnumDescriptor {
	return file_actions_proto_enumTypes[2].Descriptor()
}

func (JOINROOM_ACK) Type() protoreflect.EnumType {
	return &file_actions_proto_enumTypes[2]
}

func (x JOINROOM_ACK) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JOINROOM_ACK.Descriptor instead.
func (JOINROOM_ACK) EnumDescriptor() ([]byte, []int) {
	return file_actions_proto_rawDescGZIP(), []int{2}
}

type C2SPlayerAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid    int32  `protobuf:"varint,1,opt,name=Pid,proto3" json:"Pid,omitempty"`
	Action ACTION `protobuf:"varint,2,opt,name=action,proto3,enum=ACTION" json:"action,omitempty"`
}

func (x *C2SPlayerAction) Reset() {
	*x = C2SPlayerAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SPlayerAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SPlayerAction) ProtoMessage() {}

func (x *C2SPlayerAction) ProtoReflect() protoreflect.Message {
	mi := &file_actions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SPlayerAction.ProtoReflect.Descriptor instead.
func (*C2SPlayerAction) Descriptor() ([]byte, []int) {
	return file_actions_proto_rawDescGZIP(), []int{0}
}

func (x *C2SPlayerAction) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *C2SPlayerAction) GetAction() ACTION {
	if x != nil {
		return x.Action
	}
	return ACTION_NOACTION
}

type S2CPlayerActionAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid int32      `protobuf:"varint,1,opt,name=Pid,proto3" json:"Pid,omitempty"`
	Ack ACTION_ACK `protobuf:"varint,2,opt,name=ack,proto3,enum=ACTION_ACK" json:"ack,omitempty"`
}

func (x *S2CPlayerActionAck) Reset() {
	*x = S2CPlayerActionAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actions_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CPlayerActionAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CPlayerActionAck) ProtoMessage() {}

func (x *S2CPlayerActionAck) ProtoReflect() protoreflect.Message {
	mi := &file_actions_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CPlayerActionAck.ProtoReflect.Descriptor instead.
func (*S2CPlayerActionAck) Descriptor() ([]byte, []int) {
	return file_actions_proto_rawDescGZIP(), []int{1}
}

func (x *S2CPlayerActionAck) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *S2CPlayerActionAck) GetAck() ACTION_ACK {
	if x != nil {
		return x.Ack
	}
	return ACTION_ACK_LOGIN_SUCCESS
}

type S2CJoinRoomAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rid int32        `protobuf:"varint,1,opt,name=Rid,proto3" json:"Rid,omitempty"`
	Ack JOINROOM_ACK `protobuf:"varint,2,opt,name=ack,proto3,enum=JOINROOM_ACK" json:"ack,omitempty"`
}

func (x *S2CJoinRoomAck) Reset() {
	*x = S2CJoinRoomAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actions_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CJoinRoomAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CJoinRoomAck) ProtoMessage() {}

func (x *S2CJoinRoomAck) ProtoReflect() protoreflect.Message {
	mi := &file_actions_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CJoinRoomAck.ProtoReflect.Descriptor instead.
func (*S2CJoinRoomAck) Descriptor() ([]byte, []int) {
	return file_actions_proto_rawDescGZIP(), []int{2}
}

func (x *S2CJoinRoomAck) GetRid() int32 {
	if x != nil {
		return x.Rid
	}
	return 0
}

func (x *S2CJoinRoomAck) GetAck() JOINROOM_ACK {
	if x != nil {
		return x.Ack
	}
	return JOINROOM_ACK_JOINROOM_SUCCESS
}

var File_actions_proto protoreflect.FileDescriptor

var file_actions_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x44, 0x0a, 0x0f, 0x43, 0x32, 0x53, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x50, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x07, 0x2e, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x52, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x45, 0x0a, 0x12, 0x53, 0x32, 0x43, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x50,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x50, 0x69, 0x64, 0x12, 0x1d, 0x0a,
	0x03, 0x61, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x41, 0x43, 0x54,
	0x49, 0x4f, 0x4e, 0x5f, 0x41, 0x43, 0x4b, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x22, 0x43, 0x0a, 0x0e,
	0x53, 0x32, 0x43, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x41, 0x63, 0x6b, 0x12, 0x10,
	0x0a, 0x03, 0x52, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x52, 0x69, 0x64,
	0x12, 0x1f, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e,
	0x4a, 0x4f, 0x49, 0x4e, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x41, 0x43, 0x4b, 0x52, 0x03, 0x61, 0x63,
	0x6b, 0x2a, 0x4d, 0x0a, 0x06, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x12, 0x0c, 0x0a, 0x08, 0x4e,
	0x4f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x4f, 0x47,
	0x49, 0x4e, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x4f, 0x47, 0x4f, 0x55, 0x54, 0x10, 0x02,
	0x12, 0x10, 0x0a, 0x0c, 0x52, 0x45, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e,
	0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x4a, 0x4f, 0x49, 0x4e, 0x52, 0x4f, 0x4f, 0x4d, 0x10, 0x04,
	0x2a, 0x33, 0x0a, 0x0a, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x41, 0x43, 0x4b, 0x12, 0x11,
	0x0a, 0x0d, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10,
	0x00, 0x12, 0x12, 0x0a, 0x0e, 0x4c, 0x4f, 0x47, 0x4f, 0x55, 0x54, 0x5f, 0x53, 0x55, 0x43, 0x43,
	0x45, 0x53, 0x53, 0x10, 0x01, 0x2a, 0x24, 0x0a, 0x0c, 0x4a, 0x4f, 0x49, 0x4e, 0x52, 0x4f, 0x4f,
	0x4d, 0x5f, 0x41, 0x43, 0x4b, 0x12, 0x14, 0x0a, 0x10, 0x4a, 0x4f, 0x49, 0x4e, 0x52, 0x4f, 0x4f,
	0x4d, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x2e,
	0x2f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_actions_proto_rawDescOnce sync.Once
	file_actions_proto_rawDescData = file_actions_proto_rawDesc
)

func file_actions_proto_rawDescGZIP() []byte {
	file_actions_proto_rawDescOnce.Do(func() {
		file_actions_proto_rawDescData = protoimpl.X.CompressGZIP(file_actions_proto_rawDescData)
	})
	return file_actions_proto_rawDescData
}

var file_actions_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_actions_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_actions_proto_goTypes = []interface{}{
	(ACTION)(0),                // 0: ACTION
	(ACTION_ACK)(0),            // 1: ACTION_ACK
	(JOINROOM_ACK)(0),          // 2: JOINROOM_ACK
	(*C2SPlayerAction)(nil),    // 3: C2SPlayerAction
	(*S2CPlayerActionAck)(nil), // 4: S2CPlayerActionAck
	(*S2CJoinRoomAck)(nil),     // 5: S2CJoinRoomAck
}
var file_actions_proto_depIdxs = []int32{
	0, // 0: C2SPlayerAction.action:type_name -> ACTION
	1, // 1: S2CPlayerActionAck.ack:type_name -> ACTION_ACK
	2, // 2: S2CJoinRoomAck.ack:type_name -> JOINROOM_ACK
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_actions_proto_init() }
func file_actions_proto_init() {
	if File_actions_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_actions_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SPlayerAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actions_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CPlayerActionAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actions_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CJoinRoomAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_actions_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_actions_proto_goTypes,
		DependencyIndexes: file_actions_proto_depIdxs,
		EnumInfos:         file_actions_proto_enumTypes,
		MessageInfos:      file_actions_proto_msgTypes,
	}.Build()
	File_actions_proto = out.File
	file_actions_proto_rawDesc = nil
	file_actions_proto_goTypes = nil
	file_actions_proto_depIdxs = nil
}
